package com.github.kr328.simplefcmfix.refine;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a class whose bridge methods are rewritten by the build-time
 * {@code RefineTransformer}.
 *
 * <p>Each bridge method must be concrete, static, and annotated with exactly one of the
 * refinement annotations declared below. Its source body is only a placeholder and is discarded
 * when the class is transformed.</p>
 *
 * <p>The generated bytecode accesses the target member directly rather than through reflection.
 * A missing, inaccessible, or incompatible target therefore produces the corresponding JVM
 * linkage or access error.</p>
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.CLASS)
public @interface Refine {
    /**
     * Replaces a bridge method with a direct {@code invokevirtual} instruction.
     *
     * <p>The first bridge parameter is the invocation receiver. All remaining parameters and the
     * bridge method return type form the target method signature. When
     * {@link #value} is omitted, the receiver parameter type is used as the target owner. When
     * {@link #name} is omitted, the bridge method name is used as the target method name.</p>
     *
     * <pre>{@code
     * @Refine.InvokeVirtual(name = "withPackageName")
     * private static AttributionSource updatePackageName(
     *         AttributionSource source, String packageName) {
     *     throw new IllegalArgumentException("Stub!");
     * }
     * }</pre>
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.CLASS)
    @interface InvokeVirtual {
        /**
         * The class that owns the target method, or {@code void.class} to use the receiver
         * parameter type.
         */
        Class<?> value() default void.class;

        /**
         * The target method name, or an empty string to use the bridge method name.
         */
        String name() default "";
    }

    /**
     * Replaces a bridge method with a direct {@code invokestatic} instruction.
     *
     * <p>All bridge method parameters and the bridge return type form the target method signature.
     * When {@link #name} is omitted, the bridge method name is used as the target method name.</p>
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.CLASS)
    @interface InvokeStatic {
        /**
         * The class that owns the target static method.
         */
        Class<?> value();

        /**
         * The target method name, or an empty string to use the bridge method name.
         */
        String name() default "";
    }

    /**
     * Replaces a bridge method with a direct {@code getstatic} instruction.
     *
     * <p>The bridge method must have no parameters, and its return type must match the target
     * field type.</p>
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.CLASS)
    @interface GetStatic {
        /**
         * The class that owns the target static field.
         */
        Class<?> value();

        /**
         * The name of the target static field.
         */
        String name();
    }
}
